# Command to start on workspace startup

tasks:
  - init: |
      python3 -m venv venv
      source venv/bin/activate  
      python manage.py migrate
      echo "from django.contrib.auth import get_user_model; get_user_model().objects.create_superuser('admin', '', 'password')" | python manage.py shell
      python manage.py runserver 0.0.0.0:8000
    name: python
  - init: |
      clear
      nvm install
      npm install
      npm run gulp
    name: node
    openMode: split-right

ports:
  - port: 8000
  - port: 3000
    onOpen: open-preview
