# Command to start on workspace startup

tasks:
  - init: |
      clear
      cp app/settings/local.example.py app/settings/local.py
      echo '# required when running in gitpod' >> app/settings/local.py
      echo 'CSRF_TRUSTED_ORIGINS = ["https://*.gitpod.io"]' >> app/settings/local.py
      echo "url=$(gp url 3000)" >> .gitpod.env
      mkdir database_dumps
      pip install -U pip
      pip install poetry
      poetry config virtualenvs.in-project true
      poetry install
      source .venv/bin/activate  
      python manage.py migrate
      echo "from django.contrib.auth import get_user_model; get_user_model().objects.create_superuser('admin', '', 'password')" | python manage.py shell
      python manage.py runserver 0.0.0.0:8000
    name: python
  - init: |
      clear
      nvm install
      npm install
      gp await-port 8000
      npm run gulp
    name: node
    openMode: split-right

ports:
  - port: 8000
  - port: 3000
    onOpen: open-preview
